### ISSUE TITLE
code fails with error

### ISSUE THREAD

**Issue by rubytastic** [tokafish/pushertc#1]
Great thanks for putting the interesting blog post online but the code fails with

ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)

Have checked the config files but to no avail, any thoughts why it breaks?

**Comment by tokafish** [comment]
@rubytastic do you have PUSHER_URL set in your environment? You'll need to sign up for a Pusher account, and they should provide it to you.

If that's not the problem, do you have a complete stack trace?

**Comment by rubytastic** [comment]
@wless1 
That was indeed the problem, inside the pusher initializer there is a line 
Pusher.url = ENV['PUSHER_URL']

But this env is not defined anywhere. 
After filling this in, the code works. Thanks again for posting this usefull example!
